### ISSUE TITLE
关于Loss Function以及最终聚类结果的问题

### ISSUE THREAD

**Issue by luckylin1996** [Panern/MCGC#1]
作者你好，我尝试复现你的实验结果，但是我发现在迭代过程中，虽然目标函数的总loss是在下降，但是聚类结果也是在变差的（理论上应该越来越好）。而且算法收敛时，NMI通常都是最低的。请问是我的设置有问题吗？ 你之前有遇到过这种情况吗？

**Comment by luckylin1996** [comment]
> 作者你好，我尝试复现你的实验结果，但是我发现在迭代过程中，虽然目标函数的总loss是在下降，但是聚类结果也是在变差的（理论上应该越来越好）。而且算法收敛时，NMI通常都是最低的。请问是我的设置有问题吗？ 你之前有遇到过这种情况吗？

还有一个问题，为什么是在迭代过程中进行聚类，保存最好的聚类结果，不应该是算法收敛后再进行kmeans等聚类算法 然后保存最终结果吗？

**Comment by Panern** [comment]
> 作者你好，我尝试复现你的实验结果，但是我发现在更新过程中，虽然目标的总损失在下降，但是结果也会变的（以后应该会好）。有点算法聪明的时候，NMI 通常都是最低的。请问是我的设置有问题吗？之前有遇到过这种情况吗？

首先，谢谢您关注我们的工作。
关于您的问题，我确实遇到了，印象里实验中NMI和ACC变化不一样，就是最好的ACC的时候并不是最大的NMI, NMI在下降；第二个就是取最优的问题，首先是因为发现收敛的时候没有对应最优的ACC,其实ACC一直在变，主要是优化方式的问题吧，这种优化求出的是一个局部次优解（其实在Adam那个文件里初始的learnRate的设置影响还挺大的）。最终的结果**确实取**了最优结果的的而不是最后收敛的那个值，不过保留epoch和参数一致的话，每一轮获得的S聚类效果应该一直是一致的。
还有一点，诚实的说，部分数据集上会有更高也有低一点的结果，因为这个代码是后来整理重写的，这个仓库会保持更新，之后找到源数据或者文件的话会及时更新。

**Comment by luckylin1996** [comment]
> > 作者你好，我尝试复现你的实验结果，但是我发现在迭代过程中，虽然目标函数的总loss是在下降，但是聚类结果也是在变差的（理论上应该越来越好）。而且算法收敛时，NMI通常都是最低的。请问是我的设置有问题吗？ 你之前有遇到过这种情况吗？
> 
> 首先，谢谢您关注我们的工作。 关于您的问题，我确实遇到了，印象里实验中NMI和ACC变化不一样，就是最好的ACC的时候并不是最大的NMI, NMI在下降；第二个就是取最优的问题，首先是因为发现收敛的时候没有对应最优的ACC,其实ACC一直在变，主要是优化方式的问题吧，这种优化求出的是一个局部次优解（其实在Adam那个文件里初始的learnRate的设置影响还挺大的）。最终的结果**确实取**了最优结果的的而不是最后收敛的那个值，不过保留epoch和参数一致的话，每一轮获得的S聚类效果应该一直是一致的。 还有一点，诚实的说，部分数据集上会有更高也有低一点的结果，因为这个代码是后来整理重写的，这个仓库会保持更新，之后找到源数据或者文件的话会及时更新。

>
>可是有个问题，既然是无监督学习，是否应该在算法收敛的时候才计算ACC之类的指标呢？ 我的理解是在现实生产环境中，并不能获得真实的类标。所以，如果取迭代过程中最优解，不就意味着已经知道了最终的聚类结果了吗？这样就没有聚类的意义了。
应该是要取迭代收敛后的S，才算真正的无监督聚类吧？

**Comment by luckylin1996** [comment]
> > 作者你好，我尝试复现你的实验结果，但是我发现在更新过程中，虽然目标的总损失在下降，但是结果也会变的（以后应该会好）。有点算法聪明的时候，NMI 通常都是最低的。请问是我的设置有问题吗？之前有遇到过这种情况吗？
> 
> 首先，谢谢您关注我们的工作。 关于您的问题，我确实遇到了，印象里实验中NMI和ACC变化不一样，就是最好的ACC的时候并不是最大的NMI, NMI在下降；第二个就是取最优的问题，首先是因为发现收敛的时候没有对应最优的ACC,其实ACC一直在变，主要是优化方式的问题吧，这种优化求出的是一个局部次优解（其实在Adam那个文件里初始的learnRate的设置影响还挺大的）。最终的结果**确实取**了最优结果的的而不是最后收敛的那个值，不过保留epoch和参数一致的话，每一轮获得的S聚类效果应该一直是一致的。 还有一点，诚实的说，部分数据集上会有更高也有低一点的结果，因为这个代码是后来整理重写的，这个仓库会保持更新，之后找到源数据或者文件的话会及时更新。
>
>可是有个问题，既然是无监督学习，是否应该在算法收敛的时候才计算ACC之类的指标呢？ 我的理解是在现实生产环境中，并不能获得真实的类标。所以，如果取迭代过程中最优解，不就意味着已经知道了最终的聚类结果了吗？这样就没有聚类的意义了。
应该是要取迭代收敛后的S，才算真正的无监督聚类吧？

**Comment by luckylin1996** [comment]
可是有个问题，既然是无监督学习，是否应该在算法收敛的时候才计算ACC之类的指标呢？ 我的理解是在现实生产环境中，并不能获得真实的类标。所以，如果取迭代过程中最优解，不就意味着已经知道了最终的聚类结果了吗？这样就没有聚类的意义了。
应该是要取迭代收敛后的S，才算真正的无监督聚类吧？
